name: Deploy API and Automate Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      # - name: Install curl (for nektos/act local CI testing)
      #   run: apt-get update && apt-get install build-essential curl pkg-config openssl -y

      - name: Install PDM
        run: curl -sSL https://pdm-project.org/install-pdm.py | python3 -

      - name: Install PDM dependencies and initialize project repository
        run: pdm install

      - name: Activate Virtual Environment
        run: pdm venv activate

      - name: Install pip and other dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install types-beautifulsoup4
          python -m pip install types-requests
          python -m pip install --upgrade mypy
          pip install -r requirements.txt

      - name: Format code
        run: pdm format

      - name: Lint code
        run: pdm lint

      - name: Start project
        run: pdm run start

      - name: Run Tests
        run: pdm test